---
title: "Binomial Inference"
author: |
  | Author: Holiday Tang 
  | [LinkeDin](https://www.linkedin.com/in/holiday-t/) |  [GitHub](https://github.com/holiday007) | [Kaggle Novice](https://www.kaggle.com/holibae007)
date: "| Date: `r Sys.Date()`"
output:
  github_document:
    toc: true
    
    fig_width: 7
    fig_height: 5
    toc_depth: 3
    dev: png
---

Materials adopted from *Introduction to Categorical Analysis* by Alan Agresti 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, comment=NA, cache=T)
```

## Binomial inference

### shapes of binomial densities

```{r}
n = 25 ## of trials
pi = c(0.05, .1, .3, .5) # probability of success
par(mfrow=c(2,2))

for(i in 1:length(pi))
  plot(0:n, dbinom(0:n,n,pi[i]), type="h",
  xlab=bquote(pi == .(pi[i])), ylab="Density")

# bquote(abc = .b ~ cba = .q) 
# ".b", ".q" are referencing variable b and q, "abc", "cba", "=" are printed
# literally, also greek letters are letters here
```

### Shapes of likelihood for binomial

```{r}
par(mfrow=c(2,1))
y <- 10
curve(dbinom(y,n,x), xlim=c(0,1), xlab=expression(pi),
 main=paste("Likelihood for y =",y))

y <- 0
curve(dbinom(y,n,x), xlim=c(0,1), xlab=expression(pi),
 main=paste("Likelihood for y =",y))

# expression(pi) - gives greek version
```

### Wald CI for pi

```{r}
y <- 10
pihat <- y/n
pihat + c(-1,1) * qnorm(1-0.05/2) * sqrt(pihat*(1-pihat)/n)


y <- 0
pihat <- y/n
pihat + c(-1,1) * qnorm(1-0.05/2) * sqrt(pihat*(1-pihat)/n)
```

### Likelihood-ratio CI

```{r}
y <- 0
c(0, 1 - exp(-qchisq(1-0.05,1)/(2*n)))
```

### Score CI

```{r}
prop.test(y, n, correct=FALSE)$conf.int

# with continuity correction
prop.test(y, n)$conf.int
```

### Clopper-Pearson "exact" CI

```{r}
binom.test(y, n)$conf.int
```

### Likelihood-ratio tests

```{r}
obs <- c(26,7,9,6,4,1,2,5,0)
expected <- sum(obs) * log10(1 + 1/1:9)
( G.squared <- 2 * sum(obs * ifelse(obs>0,log(obs/expected),0)) )
```

### Pearson chi-squared test

```{r}
chisq.test(x=c(26,7,9,6,4,1,2,5,0), p=log10(1 + 1/1:9))
```

