---
title: "Insert Title"
author: |
  | Author: Holiday Tang 
  | [LinkeDin](https://www.linkedin.com/in/holiday-t/) |  [GitHub](https://github.com/holiday007) | [Kaggle Novice](https://www.kaggle.com/holibae007)
date: "| Date: `r Sys.Date()`"
output:
  github_document:
    toc: true
    fig_width: 7
    fig_height: 5
    toc_depth: 2
    dev: png
    pandoc_args: --webtex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, comment=NA, cache=T)

# install packages
packs = c("shiny", "shinydashboard")

new.pkg <- packs[!(packs %in% installed.packages())]

if (length(new.pkg)) {
  install.packages(new.pkg, repos = "http://cran.rstudio.com")
}
```

# Basics

A dashboard has three parts: a header, a sidebar, and a body. Here’s the most minimal possible UI for a dashboard page.

```{r}
## ui.R ##
library(shinydashboard)

dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody()
)
```

### Blank Dashboard

```{r}
## app.R ##
library(shiny)
library(shinydashboard)

ui = dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody()
)

server = function(input, output){}

shinyApp(ui, server)
```

### Let's add some elements

#### Adding title to header 

```{r}
## app.R ##
ui = dashboardPage(
  dashboardHeader(title = "Basic Dashboard"), # adding title
  dashboardSidebar(),
  dashboardBody(
    # Boxes need to be put in a row (or column)
    
    ############### First Row ###############
    fluidRow(
      ### column 1 ###
      box(plotOutput("plot1", height = 250)),
      
      ### column 2 ###
      box(
        title = "Controls",
        sliderInput("slider", "Number of observations:", 1, 100, 50)
      )
    )
  )
)

server = function(input, output){
  set.seed(101)
  
  output$plot1 = renderPlot({
    data = rnorm(input$slider)
    hist(data)
  })
}

shinyApp(ui, server)
```

